language: java
sudo: false
install: true

notifications:
  email: #false
    recipients:
      - chandanv89@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

addons:
  sonarcloud:
    organization: "chandanv89-github" #6b5a0375472cbb4e6d68ac8f877ffd4336375d4f
    token:
      secure: "SxMb5V8x4HzEJl3tQwH3/OAOl1rkqgvYX3FW5DDtQSWwvuuauHsxX+tQFjIq4P9hQ3//p0/rYOfxxjpLEi9F2eai158FAvcbsZkygpRE9hfS9dk0AOxDNPCrJD7dBcgjqUAJviURY4fPzV0lzbAlk5HYGcWBaPtuc1QHjQ9iQHdG8uaF9GSdSmTzL8q/Sw4xen3CL22O7LEo/0RtkTbfyFWhXmpZz45YWWfairUxfjYO+f292y9zNRG0UaPj8QASyoN1PsCc/YN+AwAuYMrVxZzN/xJo3ng9vUrc913anzTy08eCtqRUTc7ieo4s1mvkelsfrRYuZn3owMAxOXAemXitSCoVNkjquE4A9OHYTrFeMLhijo2oNyQOx5smis2qh40goijQQW5SbTqhCTNNayUBC3RjLLCZPjoBLWECGS3HF5n6D5cYmjb2fqy5pJqI9VLxNkXTTf+MWvHIufgEtJODREf6TBTvLN11NoSAvRYsFH/fN5LPetOh0NP1ufXn38Fu+4lQwoNsILVCin+vPfw73YkpT1QZT5R+JKlCXbaDcLxkyXN0AyBn+p4q9rNuZdmu4fouQQuJ48ahru5NmKWmQ/xlJQ3r2EKBvlW2YzMrKhvYBiRfA6AAHL5Bdsk54LQNr/OFGUaOFSiuOtf796xKE1DPDvA5+u2zKheCDws="
    branches:
      - master
      - develop
      - 2018.03
jdk:
  - oraclejdk8
script:
  - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'