language: java
sudo: false
install: true

jdk:
  - oraclejdk8

notifications:
  email: #false
    recipients:
      - chandanv89@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

addons:
  sonarcloud:
    organization: "chandanv89-github" #http://travis-encrypt.github.io/6b5a0375472cbb4e6d68ac8f877ffd4336375d4f
    token:
      secure: "vygEjqOlwvpfbq50lwqaQht0KDGgBraFJ2bmIhMr/3M3Gdwiv2oT/riSVGxe4bXxV3DyTpap8FQ/HJ6Fc+KCQs53t3opphFv3Yh2G4DfHhNhZnjxva2iZnH+xnvfma4QkFbG2U7elbzyvMrjCXYWYJo1SfJwuwcDqyjRkycD2yDq7BrB3utuUFBS4vgIOmnuKu+Em5rMNtNE9sKwo5RfN+u/B85CMJ5PO21rHS6xcOb41UXSx5xq8s/2cz3Eh28eQtuZ8zKmUAER+Hs+d3uIxCk5k7WknHV4JxN8KCCxsMkBJgA3wXqydUhHAe+0KLUQwsfrUBQxRW3jLxWHTEjPdwlA7kpFlU8kXp2lypHN31D8kq6Ey+QjV5xn0uNwkOdSC29FPzw9ZHTSFP0lJPE202r0zydMZKJglRlLkS8sakUce23YonDLihYPKVmI5r/ayu2nTZ9aV4BvEccsJA1kOq6p/UQsUTkOBCefZ1cnavJfuBHwscCoI45YE3vOTY9RRIfbN11PRkxH41+ecch3KIYGcD8NZmBMqBzM9YCqCwAYuS9I46s7ZEKbvnTkk2cdRCGV3nshAa3DpK2F1/oAPg88IiPx+sfX5pH66zEUN9+Za2aHLHegbrwnUj48BSj7pOiSckCPpQN30wZ5/FktsdA1PiYfmuhIkroDFglZ8NE="
    branches:
      - master
      - develop

script:
  - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'