language: java
sudo: false
install: true

jdk:
  - oraclejdk8

notifications:
  email: #false
    recipients:
      - chandanv89@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

addons:
  sonarcloud:
    organization: "chandanv89-github"
    token:
      secure: "xcM6NIt+6RWyuv/FbXOw4vhYdxhRAsLQal7QpTZysZQ2l3FqK/+SFS0QYFJuU+2TiyZQrXE6eZBdvUBxnNMRNHAtegLsUSaS5psRgJj+NMMD/Z88zFOe2tnqfbJRsm27OhokgLX56WZod13fg9NPxRW8CaD++RhkyjSEKQrWnbsACqh5Q7v3vHfGqbEKX3tqMAuKJsAHGit2p5Z7/MmYxxXwI3BwWlmknyVoe9xLfiNB8wDRnxplyVaJTr/5ffw7HPiUIjn3kLd+TP4YSEHp+kuiPDghIHkHVS/yHwOywaz94n0cYUcqQiftphNjweuCDEqlQvv6bsAOSKpfluiW0sJNChh3MupJuImW8oJSKg1F4Rba80R2+rVt2vWAHlxRs4OeiJXWmzBBHsIseoZqFPDBeehNLyPJNri6G7ZU5ERUiw1DUS4eWwZLuNIOY2lrEayXr05pIb4fswAsi2VUT5UsJ3uxCw8IdhZAkLdJYtBFJdlae6Wm/bGcTyaQx01K1RaO3hqEo7wLb5BVG4Vg6yNYCQDPGFCVPWQS8NLcbIToIRLf83Gta3n9W8884q2xhMjX3Ddza5iXKpPEB+GkMV8Juey6k1zUdqShKh8JzgqZ12czDsWEKYhqrj9UlJLSxO+U4X2I356j3TSt+8nP6bMD2f5Qy4itxfewvQmC/wg="
    #branches:
      #- master
      #- develop

script:
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=chandanv89-github -Dsonar.login=6b5a0375472cbb4e6d68ac8f877ffd4336375d4f -Dsonar.branch.name=develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
